name: DLA
channels:
  - conda-forge
dependencies:
  - python=3.13
  - jupyterlab=4.3.5
  - ipython=9.0.2
  - matplotlib=3.10.1
  - scikit-learn=1.6.1
  - tqdm=4.67.1
  - pytorch=2.6.0
  - torchvision=0.21.0
  - tensorboard=2.19.0
  - standard-imghdr=3.13.0
  - numpy=2.2.3
  - pillow=11.1.0
  - pyyaml=6.0.2